
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "WarriorUnit.sol";
import "Base.sol";

// This is class that describes you smart contract.
contract Archer is WarriorUnit {

    uint public NumberOfArrows;
    function getNumberOfArrows(uint value) public checkOwnerAndAccept {
        NumberOfArrows=value;
    }

}