
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "WarriorUnit.sol";

// This is class that describes you smart contract.
contract Warrior is WarriorUnit{
    uint public numberOfSwords;
    
    function getNumberOfSwords(uint value) public checkOwnerAndAccept {
        numberOfSwords=value;
    }
}
